#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if grep -q fstabkey:uuid $FAI/disk_config/* ; then
  error=1
fi
grep '^UUID=' $FAI_ROOT/etc/fstab

exit $error
